### ISSUE TITLE
met error

### ISSUE THREAD

**Issue by zhaobingbingbing** [koichiro11/residual-attention-network#4]
Hey,when I run this code
there is an error
` File "/home/user/anaconda3/envs/tf1.4/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 1224, in __init__
    layer.outbound_nodes.append(self)
AttributeError: 'UpSampling2D' object has no attribute 'outbound_nodes'`
Do you know how to fix it?
Thank you .

**Comment by NatalieZou** [comment]
@zhaobingbingbing  I met the same error , do you solve it?

**Comment by CRazorback** [comment]
@koichiro11 So do I.
Traceback (most recent call last):
  File "C:\Users\MSI-PC\Documents\GitHub\residual-attention-network\train.py", line 31, in <module>
    y = model.f_prop(x)
  File "C:\Users\MSI-PC\Documents\GitHub\residual-attention-network\model\residual_attention_network.py", line 44, in f_prop
    x = self.attention_module.f_prop(x, input_channels=64, scope="attention_module_1", is_training=is_training)
  File "C:\Users\MSI-PC\Documents\GitHub\residual-attention-network\model\attention_module.py", line 89, in f_prop
    output_soft_mask = tf.layers.conv2d(output_soft_mask, filters=input_channels, kernel_size=1)
  File "C:\Users\MSI-PC\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\layers\convolutional.py", line 621, in conv2d
    return layer.apply(inputs)
  File "C:\Users\MSI-PC\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\layers\base.py", line 828, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "C:\Users\MSI-PC\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\layers\base.py", line 787, in __call__
    input_tensors=inputs, output_tensors=outputs, arguments=user_kwargs)
  File "C:\Users\MSI-PC\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\layers\base.py", line 864, in _add_inbound_node
    arguments=arguments)
  File "C:\Users\MSI-PC\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\layers\base.py", line 1376, in __init__
    layer.outbound_nodes.append(self)
AttributeError: 'UpSampling2D' object has no attribute 'outbound_nodes'

**Comment by alyato** [comment]
hi，i meet the same error.
how to fix it?
thanks
python's version is 2.7

**Comment by sankin1770** [comment]
Maybe you could try   _outbound_nodes

**Comment by Albert337** [comment]
hi,i meet the problem too.Is there anyone who sloved it?I would be appreciated if you'd like to help me.

**Comment by zhuobielindesamoye** [comment]
maybe you could use keras.version=2.0.9

**Comment by zhuobielindesamoye** [comment]
> @zhaobingbingbing I met the same error , do you solve it?



> Hey,when I run this code
> there is an error
> ` File "/home/user/anaconda3/envs/tf1.4/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 1224, in __init__ layer.outbound_nodes.append(self) AttributeError: 'UpSampling2D' object has no attribute 'outbound_nodes'`
> Do you know how to fix it?
> Thank you .

i try to use keras.version=2.0.9,maybe it can help u.But i met another error.
Traceback (most recent call last):
  File "F:/residual-attention-network-master/train.py", line 39, in <module>
    print("train_X: {shape}".format(shape=train_X.shape))
AttributeError: 'dict' object has no attribute 'shape'
how to fix it .thanks

**Comment by xiaohujecky** [comment]
change the File "/home/user/anaconda3/envs/tf1.4/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 1224, in __init__ layer.outbound_nodes.append(self) to 
layer._outbound_nodes.append(self)
